# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa36d05382e2cf87070fbba0be7851eaab2ff78761f7f1a5f87457c65b721aae4970548d878b9f0816f9361bd4b180f467a176f145ab257b6049f1e1057dfc4

test:
  secret_key_base: fc0dbcc5d1ae237ee33d9e06b762b004df7b5bb22801b3fb8339654c7ac6963b990d63dbbad1ffcb146ae8ce8594d4cf81c7f77c582078206fc96ccbce85330e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
